FROM node:20-alpine

WORKDIR /app

# Install dependencies for hot reloading
RUN apk add --no-cache libc6-compat git

# Copy package files
COPY package*.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Expose port 3000
EXPOSE 3000

# Enable hot reloading
ENV WATCHPACK_POLLING true
ENV NEXT_TELEMETRY_DISABLED 1

CMD ["npm", "run", "dev"]
